#!/bin/bash
# pre-commit-spaced-worktree-verify.sh — regression fixture for the
# code-lead Major finding (g-docs/agent-output/review/code-lead-2026-07-15.md,
# hooks/pre-commit:105-106): gf_parse_stamp's STAMP_WORKTREE parse truncated
# the TERMINAL commit_sentinel_worktree field at the first space, while the
# live-computed WORKTREE_KEY it is compared against is never truncated.
# Worktree paths legitimately contain spaces (common on Windows).
#
# Promoted from a session scratchpad (spaced-worktree-verify.sh) into
# g-dev/fixtures/ per the g-dev/README.md promotion rule. The original
# scratchpad script also ran a FAIL-BEFORE scenario against a pre-fix copy
# of hooks/pre-commit extracted via `git show HEAD:hooks/pre-commit` at the
# time of that session. That half is dropped here: it depended on a
# snapshot of the pre-fix hook that does not exist in this promoted
# fixture's environment, and the fix is now permanently in hooks/pre-commit
# on main — there is no "before" state left to demonstrate against. This
# fixture keeps only the two scenarios that verify current behavior:
#   1. PASS — a correctly-stamped commit under a SPACED worktree path is
#      accepted (the regression this fixture guards against reintroducing).
#   2. CONTROL — a deliberately wrong-worktree stamp (still under a spaced
#      path) is still correctly DENIED, proving the fix only stopped
#      truncating the field; it did not weaken the worktree-mismatch check.
#
# This script builds temp git repos under SPACED directory names, stamps
# them with fields generated by RUNNING the real git commands (never
# hand-typed literals), then drives hooks/pre-commit directly.
#
# Reuses the same helper conventions as pre-commit-gate-verify.sh (new_repo,
# gate_tier, initial_commit, stage_code_file, write_sentinel, run_precommit).

set -u

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="${GFORGE_REPO_ROOT:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
PRECOMMIT="$REPO_ROOT/hooks/pre-commit"
# Spaced base dir — this is the entire point of the fixture.
BASE="$(mktemp -d)/sandbox tmp"

if [ ! -f "$PRECOMMIT" ]; then
    echo "FATAL: cannot find hooks/pre-commit at $PRECOMMIT" >&2
    exit 1
fi

echo "=== Spaced-worktree regression fixture (code-lead Major finding) ==="
echo "REPO_ROOT=$REPO_ROOT"
echo "PRECOMMIT=$PRECOMMIT"
echo "BASE (spaced temp repos)=$BASE"
echo

mkdir -p "$BASE"

TOTAL_PASS=0
TOTAL_FAIL=0

check() {
    # check <name> <1|0> <detail>
    local name="$1" ok="$2" detail="$3"
    if [ "$ok" = "1" ]; then
        echo "PASS: $name"
        TOTAL_PASS=$((TOTAL_PASS + 1))
    else
        echo "FAIL: $name -- $detail"
        TOTAL_FAIL=$((TOTAL_FAIL + 1))
    fi
}

# --- fixture helpers (mirrors pre-commit-gate-verify.sh) -------------------

new_repo() {
    # new_repo <dir> -> git-init's a fresh repo at the given absolute path
    local dir="$1"
    rm -rf "$dir"
    mkdir -p "$dir"
    git -C "$dir" init -q
    git -C "$dir" config user.email "test@g-forge.local"
    git -C "$dir" config user.name "g-forge-test"
}

gate_tier() {
    # gate_tier <dir> <value>
    local dir="$1" value="$2"
    mkdir -p "$dir/.claude"
    printf '%s\n' "$value" > "$dir/.claude/integration-tier"
}

initial_commit() {
    # initial_commit <dir> — establishes a HEAD so later stamps are non-empty
    local dir="$1"
    printf 'seed\n' > "$dir/README.md"
    git -C "$dir" add README.md
    git -C "$dir" commit -q -m "seed"
}

stage_code_file() {
    # stage_code_file <dir> <path>  (path must classify CODE per classify-changeset.sh)
    local dir="$1" path="$2"
    mkdir -p "$dir/$(dirname "$path")"
    printf '#!/bin/bash\necho hi\n' > "$dir/$path"
    git -C "$dir" add "$path"
}

write_sentinel() {
    # write_sentinel <file> <tree> <head> <worktree>
    local file="$1" tree="$2" head="$3" worktree="$4"
    mkdir -p "$(dirname "$file")"
    printf 'commit_sentinel_ts=%s commit_sentinel_head=%s commit_sentinel_worktree=%s\n' \
        "$tree" "$head" "$worktree" > "$file"
}

run_precommit() {
    # run_precommit <dir> — invokes hooks/pre-commit with cwd=<dir>, no stdin.
    # Sets LAST_CODE, LAST_OUT, LAST_ERR.
    local dir="$1"
    (
        cd "$dir" || exit 99
        bash "$PRECOMMIT" >"$dir/.pc.out" 2>"$dir/.pc.err"
        echo $? > "$dir/.pc.code"
    )
    LAST_CODE=$(cat "$dir/.pc.code")
    LAST_OUT=$(cat "$dir/.pc.out")
    LAST_ERR=$(cat "$dir/.pc.err")
    echo "  \$ (cd '$dir' && bash hooks/pre-commit)"
    echo "  exit code: $LAST_CODE"
    echo "  stdout: ${LAST_OUT:-<empty>}"
    echo "  stderr: ${LAST_ERR:-<empty>}"
}

# ============================================================================
echo "--- Scenario 1 (PASS): correctly-stamped commit under a SPACED"
echo "    worktree path is accepted ---"
REPO="$BASE/repo one"
new_repo "$REPO"
gate_tier "$REPO" full
initial_commit "$REPO"
stage_code_file "$REPO" "hooks/spaced1.sh"
TREE=$(git -C "$REPO" write-tree)
HEAD=$(git -C "$REPO" rev-parse --verify HEAD)
WT=$(git -C "$REPO" rev-parse --show-toplevel)
write_sentinel "$REPO/.claude/g-forge-approved" "$TREE" "$HEAD" "$WT"
echo "  repo toplevel (contains a space): $WT"
echo "  correct stamp: ts=$TREE head=$HEAD worktree=$WT"
run_precommit "$REPO"
check "1a: exit 0 on correctly-stamped spaced-path commit" "$([ "$LAST_CODE" -eq 0 ] && echo 1 || echo 0)" "exit=$LAST_CODE"
check "1b: sentinel consumed (file gone) immediately after" "$([ ! -f "$REPO/.claude/g-forge-approved" ] && echo 1 || echo 0)" "file still present: $REPO/.claude/g-forge-approved"
echo

# ============================================================================
echo "--- Scenario 2 (CONTROL): wrong-worktree stamp under the same spaced"
echo "    base must still DENY ---"
REPO="$BASE/repo two"
new_repo "$REPO"
gate_tier "$REPO" full
initial_commit "$REPO"
stage_code_file "$REPO" "hooks/spaced2.sh"
TREE=$(git -C "$REPO" write-tree)
HEAD=$(git -C "$REPO" rev-parse --verify HEAD)
REAL_WT=$(git -C "$REPO" rev-parse --show-toplevel)
WRONG_WT="${REAL_WT}-not the real worktree"
write_sentinel "$REPO/.claude/g-forge-approved" "$TREE" "$HEAD" "$WRONG_WT"
echo "  repo toplevel (contains a space): $REAL_WT"
echo "  stamp taken with WRONG worktree (also spaced): $WRONG_WT"
run_precommit "$REPO"
check "2a: exit non-zero on genuine worktree mismatch" "$([ "$LAST_CODE" -ne 0 ] && echo 1 || echo 0)" "exit=$LAST_CODE"
LC_ERR=$(printf '%s' "$LAST_ERR" | tr '[:upper:]' '[:lower:]')
check "2b: reason names the worktree mismatch" "$(case "$LC_ERR" in *worktree*) echo 1;; *) echo 0;; esac)" "stderr='$LAST_ERR'"
echo

# ============================================================================
echo "=== SUMMARY ==="
echo "PASS: $TOTAL_PASS"
echo "FAIL: $TOTAL_FAIL"

rm -rf "$BASE"

if [ "$TOTAL_FAIL" -ne 0 ]; then
    exit 1
fi
exit 0
