#!/bin/bash
# pre-commit-gate-verify.sh — sandbox verification of hooks/pre-commit
# against the commit-gate contract (ADR-004, ADR-005, skills/g-review/
# SKILL.md Step 6's stamp-write commands, hooks/lib/classify-changeset.sh's
# bucket table).
#
# Promoted from a session scratchpad (w1-2-sandbox-verify.sh, W1.2 task 10)
# into g-dev/fixtures/ per the g-dev/README.md promotion rule.
#
# VERIFICATION-ONLY: this script never edits hooks/pre-commit,
# hooks/check-commit.sh, or hooks/lib/*. It builds its fixtures from the
# CONTRACTS above — not from reading hooks/pre-commit's own implementation.
#
# Invocation choice (documented per the original task instructions): this
# script does NOT wire git's core.hooksPath. It invokes hooks/pre-commit
# directly via `bash "$PRECOMMIT"` with cwd set to the temp repo root — the
# same cwd contract git itself uses when invoking a native hook (repo root,
# no stdin payload). Because core.hooksPath is never configured, any `git
# commit` used to build fixture state (e.g. scenario c's "advance HEAD"
# setup commit) does NOT trigger the hook — this is what the original task
# called "bypass hook for the setup commit", achieved for free by never
# wiring the hook into git's own dispatch.
#
# All stamps are generated by RUNNING the same git commands the g-review
# skill specifies (git write-tree, git rev-parse HEAD, git rev-parse
# --show-toplevel) via `git -C <repo>` — never hand-typed literals.
#
# One deliberate deviation, discovered empirically while building this
# fixture: on a repo with zero commits, plain `git rev-parse HEAD`
# does NOT print nothing — it prints the literal string "HEAD" to stdout
# (with the real error on stderr, exit 0 from a `2>/dev/null` capture).
# SKILL.md Step 6 literally specifies `git rev-parse HEAD` with no
# `--verify`, but ADR-004/the plan's stated intent is an EMPTY
# commit_sentinel_head on a first commit, and hooks/pre-commit was
# empirically confirmed to treat only a truly-empty value as matching its
# own no-HEAD state — a literal "HEAD" stamp is REJECTED as stale. This
# fixture uses `git rev-parse --verify HEAD 2>/dev/null` (empty stdout on
# failure, identical stdout to plain rev-parse when HEAD exists) to
# reproduce the documented "empty" intent rather than the literal SKILL.md
# command, which would not fulfil that intent. This is a residual finding,
# not a silent workaround.

set -u

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="${GFORGE_REPO_ROOT:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
PRECOMMIT="$REPO_ROOT/hooks/pre-commit"
BASE="$(mktemp -d)"

if [ ! -f "$PRECOMMIT" ]; then
    echo "FATAL: cannot find hooks/pre-commit at $PRECOMMIT" >&2
    exit 1
fi

echo "=== pre-commit-gate-verify — sandbox verification of hooks/pre-commit ==="
echo "REPO_ROOT=$REPO_ROOT"
echo "PRECOMMIT=$PRECOMMIT"
echo "BASE (temp repos)=$BASE"
echo

TOTAL_PASS=0
TOTAL_FAIL=0

check() {
    # check <name> <1|0> <detail>
    local name="$1" ok="$2" detail="$3"
    if [ "$ok" = "1" ]; then
        echo "PASS: $name"
        TOTAL_PASS=$((TOTAL_PASS + 1))
    else
        echo "FAIL: $name -- $detail"
        TOTAL_FAIL=$((TOTAL_FAIL + 1))
    fi
}

# --- fixture helpers -------------------------------------------------------

new_repo() {
    # new_repo <name> -> prints absolute path of a freshly git-init'd repo
    local name="$1"
    local dir="$BASE/$name"
    rm -rf "$dir"
    mkdir -p "$dir"
    git -C "$dir" init -q
    git -C "$dir" config user.email "test@g-forge.local"
    git -C "$dir" config user.name "g-forge-test"
    printf '%s' "$dir"
}

gate_tier() {
    # gate_tier <dir> <value>
    local dir="$1" value="$2"
    mkdir -p "$dir/.claude"
    printf '%s\n' "$value" > "$dir/.claude/integration-tier"
}

initial_commit() {
    # initial_commit <dir> — establishes a HEAD so later stamps are non-empty
    local dir="$1"
    printf 'seed\n' > "$dir/README.md"
    git -C "$dir" add README.md
    git -C "$dir" commit -q -m "seed"
}

stage_code_file() {
    # stage_code_file <dir> <path>  (path must classify CODE per classify-changeset.sh)
    local dir="$1" path="$2"
    mkdir -p "$dir/$(dirname "$path")"
    printf '#!/bin/bash\necho hi\n' > "$dir/$path"
    git -C "$dir" add "$path"
}

stage_doc_file() {
    # stage_doc_file <dir> <path>  (path must classify DOC per classify-changeset.sh)
    local dir="$1" path="$2"
    mkdir -p "$dir/$(dirname "$path")"
    printf '# doc\n' > "$dir/$path"
    git -C "$dir" add "$path"
}

write_sentinel() {
    # write_sentinel <file> <tree> <head> <worktree>
    local file="$1" tree="$2" head="$3" worktree="$4"
    mkdir -p "$(dirname "$file")"
    printf 'commit_sentinel_ts=%s commit_sentinel_head=%s commit_sentinel_worktree=%s\n' \
        "$tree" "$head" "$worktree" > "$file"
}

run_precommit() {
    # run_precommit <dir> — invokes hooks/pre-commit with cwd=<dir>, no stdin.
    # Sets LAST_CODE, LAST_OUT, LAST_ERR.
    local dir="$1"
    (
        cd "$dir" || exit 99
        bash "$PRECOMMIT" >"$dir/.pc.out" 2>"$dir/.pc.err"
        echo $? > "$dir/.pc.code"
    )
    LAST_CODE=$(cat "$dir/.pc.code")
    LAST_OUT=$(cat "$dir/.pc.out")
    LAST_ERR=$(cat "$dir/.pc.err")
    echo "  \$ (cd $dir && bash hooks/pre-commit)"
    echo "  exit code: $LAST_CODE"
    echo "  stdout: ${LAST_OUT:-<empty>}"
    echo "  stderr: ${LAST_ERR:-<empty>}"
}

first_line() {
    printf '%s\n' "$1" | head -n1
}

# ============================================================================
echo "--- Scenario a: unstamped commit denied (gated, staged code, no sentinel) ---"
REPO=$(new_repo "a-unstamped")
gate_tier "$REPO" full
initial_commit "$REPO"
stage_code_file "$REPO" "hooks/a.sh"
echo "  staged: hooks/a.sh (CODE bucket); no sentinel written"
run_precommit "$REPO"
check "a: exit non-zero when unstamped" "$([ "$LAST_CODE" -ne 0 ] && echo 1 || echo 0)" "exit=$LAST_CODE"
FL=$(first_line "$LAST_ERR")
check "a: stderr starts with 'G-Forge:'" "$(case "$FL" in "G-Forge:"*) echo 1;; *) echo 0;; esac)" "first stderr line='$FL'"
echo

# ============================================================================
echo "--- Scenario b: stale-tree sentinel denied ---"
REPO=$(new_repo "b-stale-tree")
gate_tier "$REPO" full
initial_commit "$REPO"
stage_code_file "$REPO" "hooks/b.sh"
TREE=$(git -C "$REPO" write-tree)
HEAD=$(git -C "$REPO" rev-parse --verify HEAD)
WT=$(git -C "$REPO" rev-parse --show-toplevel)
write_sentinel "$REPO/.claude/g-forge-approved" "$TREE" "$HEAD" "$WT"
echo "  stamp taken: ts=$TREE head=$HEAD worktree=$WT"
# Change staged content AFTER the stamp — the staged tree now differs.
printf '#!/bin/bash\necho changed\n' > "$REPO/hooks/b.sh"
git -C "$REPO" add hooks/b.sh
NEWTREE=$(git -C "$REPO" write-tree)
echo "  staged content changed post-stamp; new write-tree=$NEWTREE (differs from stamped ts=$TREE: $([ "$NEWTREE" != "$TREE" ] && echo yes || echo NO))"
run_precommit "$REPO"
check "b: exit non-zero on stale tree" "$([ "$LAST_CODE" -ne 0 ] && echo 1 || echo 0)" "exit=$LAST_CODE"
echo

# ============================================================================
echo "--- Scenario c: stale-HEAD sentinel denied ---"
REPO=$(new_repo "c-stale-head")
gate_tier "$REPO" full
initial_commit "$REPO"
stage_code_file "$REPO" "hooks/c.sh"
TREE0=$(git -C "$REPO" write-tree)
HEAD0=$(git -C "$REPO" rev-parse --verify HEAD)
WT=$(git -C "$REPO" rev-parse --show-toplevel)
write_sentinel "$REPO/.claude/g-forge-approved" "$TREE0" "$HEAD0" "$WT"
echo "  stamp taken: ts=$TREE0 head=$HEAD0 worktree=$WT"
# Advance HEAD via a commit that bypasses the hook (core.hooksPath is never
# wired in this fixture, so this plain commit never invokes hooks/pre-commit).
git -C "$REPO" commit -q -m "setup: advance head (bypasses hook)"
HEAD1=$(git -C "$REPO" rev-parse --verify HEAD)
echo "  HEAD advanced via bypassed commit: HEAD0=$HEAD0 -> HEAD1=$HEAD1 (moved: $([ "$HEAD1" != "$HEAD0" ] && echo yes || echo NO))"
# Re-stage the same tree — index already equals TREE0 post-commit; re-add
# explicitly to make the "re-staged" step observable.
git -C "$REPO" add -A
CURTREE=$(git -C "$REPO" write-tree)
echo "  re-staged tree=$CURTREE (matches stamped ts=$TREE0: $([ "$CURTREE" = "$TREE0" ] && echo yes || echo NO))"
run_precommit "$REPO"
check "c: exit non-zero on stale HEAD (tree still matches, HEAD moved)" "$([ "$LAST_CODE" -ne 0 ] && echo 1 || echo 0)" "exit=$LAST_CODE"
echo

# ============================================================================
echo "--- Scenario d: worktree-mismatched sentinel denied ---"
REPO=$(new_repo "d-worktree-mismatch")
gate_tier "$REPO" full
initial_commit "$REPO"
stage_code_file "$REPO" "hooks/d.sh"
TREE=$(git -C "$REPO" write-tree)
HEAD=$(git -C "$REPO" rev-parse --verify HEAD)
REAL_WT=$(git -C "$REPO" rev-parse --show-toplevel)
WRONG_WT="${REAL_WT}-not-the-real-worktree"
write_sentinel "$REPO/.claude/g-forge-approved" "$TREE" "$HEAD" "$WRONG_WT"
echo "  stamp taken with WRONG worktree: ts=$TREE head=$HEAD worktree=$WRONG_WT (real=$REAL_WT)"
run_precommit "$REPO"
check "d: exit non-zero on worktree mismatch" "$([ "$LAST_CODE" -ne 0 ] && echo 1 || echo 0)" "exit=$LAST_CODE"
FL=$(first_line "$LAST_ERR")
LC_ERR=$(printf '%s' "$LAST_ERR" | tr '[:upper:]' '[:lower:]')
check "d: reason names the worktree mismatch" "$(case "$LC_ERR" in *worktree*) echo 1;; *) echo 0;; esac)" "stderr='$LAST_ERR'"
echo

# ============================================================================
echo "--- Scenario e: matching stamp passes AND consumes ---"
REPO=$(new_repo "e-match")
gate_tier "$REPO" full
initial_commit "$REPO"
stage_code_file "$REPO" "hooks/e.sh"
TREE=$(git -C "$REPO" write-tree)
HEAD=$(git -C "$REPO" rev-parse --verify HEAD)
WT=$(git -C "$REPO" rev-parse --show-toplevel)
write_sentinel "$REPO/.claude/g-forge-approved" "$TREE" "$HEAD" "$WT"
echo "  correct stamp: ts=$TREE head=$HEAD worktree=$WT"
run_precommit "$REPO"
check "e: exit 0 on matching stamp" "$([ "$LAST_CODE" -eq 0 ] && echo 1 || echo 0)" "exit=$LAST_CODE"
check "e: sentinel consumed (file gone) immediately after" "$([ ! -f "$REPO/.claude/g-forge-approved" ] && echo 1 || echo 0)" "file still present: $REPO/.claude/g-forge-approved"
echo

# ============================================================================
echo "--- Scenario f: first-commit both ways ---"
echo "  f1: fresh repo, no HEAD, staged code, unstamped -> deny"
REPO=$(new_repo "f1-first-unstamped")
gate_tier "$REPO" full
stage_code_file "$REPO" "hooks/f1.sh"
HEAD_CHECK=$(git -C "$REPO" rev-parse --verify HEAD 2>/dev/null)
echo "  confirmed no HEAD yet: '$HEAD_CHECK' (expected empty)"
run_precommit "$REPO"
check "f1: exit non-zero, first commit unstamped" "$([ "$LAST_CODE" -ne 0 ] && echo 1 || echo 0)" "exit=$LAST_CODE"

echo "  f2: fresh repo, no HEAD, staged code, stamped with empty head matching empty HEAD -> pass"
REPO=$(new_repo "f2-first-stamped")
gate_tier "$REPO" full
stage_code_file "$REPO" "hooks/f2.sh"
TREE=$(git -C "$REPO" write-tree)
HEAD=$(git -C "$REPO" rev-parse --verify HEAD 2>/dev/null)
WT=$(git -C "$REPO" rev-parse --show-toplevel)
write_sentinel "$REPO/.claude/g-forge-approved" "$TREE" "$HEAD" "$WT"
echo "  stamp taken: ts=$TREE head='$HEAD' (empty, matches empty current HEAD) worktree=$WT"
run_precommit "$REPO"
check "f2: exit 0, correctly-stamped first commit" "$([ "$LAST_CODE" -eq 0 ] && echo 1 || echo 0)" "exit=$LAST_CODE"
echo

# ============================================================================
echo "--- Scenario g: light tier bypasses regardless of sentinel state ---"
REPO=$(new_repo "g-light")
gate_tier "$REPO" light
initial_commit "$REPO"
stage_code_file "$REPO" "hooks/g.sh"
echo "  tier=light; no sentinel written"
run_precommit "$REPO"
check "g: exit 0 under light tier, no sentinel" "$([ "$LAST_CODE" -eq 0 ] && echo 1 || echo 0)" "exit=$LAST_CODE"
echo

# ============================================================================
echo "--- Scenario h: non-gated project bypasses (no .claude/integration-tier anywhere) ---"
REPO=$(new_repo "h-nongated")
initial_commit "$REPO"
stage_code_file "$REPO" "hooks/h.sh"
echo "  no .claude/integration-tier written anywhere"
run_precommit "$REPO"
check "h: exit 0, non-gated project" "$([ "$LAST_CODE" -eq 0 ] && echo 1 || echo 0)" "exit=$LAST_CODE"
echo

# ============================================================================
echo "--- Scenario i: mixed class requires both sentinels ---"

echo "  i1: code sentinel valid, doc sentinel MISSING -> deny naming doc"
REPO=$(new_repo "i1-mixed-doc-missing")
gate_tier "$REPO" full
initial_commit "$REPO"
stage_code_file "$REPO" "hooks/i1.sh"
stage_doc_file "$REPO" "g-docs/i1.md"
TREE=$(git -C "$REPO" write-tree)
HEAD=$(git -C "$REPO" rev-parse --verify HEAD)
WT=$(git -C "$REPO" rev-parse --show-toplevel)
write_sentinel "$REPO/.claude/g-forge-approved" "$TREE" "$HEAD" "$WT"
echo "  code sentinel: ts=$TREE head=$HEAD worktree=$WT; no doc sentinel"
run_precommit "$REPO"
check "i1: exit non-zero, doc sentinel missing" "$([ "$LAST_CODE" -ne 0 ] && echo 1 || echo 0)" "exit=$LAST_CODE"
LC_ERR=$(printf '%s' "$LAST_ERR" | tr '[:upper:]' '[:lower:]')
check "i1: reason names doc as missing/invalid" "$(case "$LC_ERR" in *doc*) echo 1;; *) echo 0;; esac)" "stderr='$LAST_ERR'"

echo "  i2: doc sentinel valid, code sentinel MISSING -> deny naming code"
REPO=$(new_repo "i2-mixed-code-missing")
gate_tier "$REPO" full
initial_commit "$REPO"
stage_code_file "$REPO" "hooks/i2.sh"
stage_doc_file "$REPO" "g-docs/i2.md"
TREE=$(git -C "$REPO" write-tree)
HEAD=$(git -C "$REPO" rev-parse --verify HEAD)
WT=$(git -C "$REPO" rev-parse --show-toplevel)
write_sentinel "$REPO/.claude/g-forge-docs-approved" "$TREE" "$HEAD" "$WT"
echo "  doc sentinel: ts=$TREE head=$HEAD worktree=$WT; no code sentinel"
run_precommit "$REPO"
check "i2: exit non-zero, code sentinel missing" "$([ "$LAST_CODE" -ne 0 ] && echo 1 || echo 0)" "exit=$LAST_CODE"
LC_ERR=$(printf '%s' "$LAST_ERR" | tr '[:upper:]' '[:lower:]')
check "i2: reason names code as missing/invalid" "$(case "$LC_ERR" in *code*) echo 1;; *) echo 0;; esac)" "stderr='$LAST_ERR'"

echo "  i3: BOTH sentinels valid -> exit 0 and BOTH consumed"
REPO=$(new_repo "i3-mixed-both-valid")
gate_tier "$REPO" full
initial_commit "$REPO"
stage_code_file "$REPO" "hooks/i3.sh"
stage_doc_file "$REPO" "g-docs/i3.md"
TREE=$(git -C "$REPO" write-tree)
HEAD=$(git -C "$REPO" rev-parse --verify HEAD)
WT=$(git -C "$REPO" rev-parse --show-toplevel)
write_sentinel "$REPO/.claude/g-forge-approved" "$TREE" "$HEAD" "$WT"
write_sentinel "$REPO/.claude/g-forge-docs-approved" "$TREE" "$HEAD" "$WT"
echo "  both sentinels: ts=$TREE head=$HEAD worktree=$WT"
run_precommit "$REPO"
check "i3: exit 0, both sentinels valid" "$([ "$LAST_CODE" -eq 0 ] && echo 1 || echo 0)" "exit=$LAST_CODE"
check "i3: code sentinel consumed" "$([ ! -f "$REPO/.claude/g-forge-approved" ] && echo 1 || echo 0)" "file still present"
check "i3: doc sentinel consumed" "$([ ! -f "$REPO/.claude/g-forge-docs-approved" ] && echo 1 || echo 0)" "file still present"
echo

# ============================================================================
echo "--- Scenario j1: DOC-only class denied without valid doc sentinel (two sub-cases) ---"

echo "  j1a: fresh repo, tier full, doc-only staged, NO sentinels -> deny naming doc"
REPO=$(new_repo "j1a-doc-no-sentinel")
gate_tier "$REPO" full
initial_commit "$REPO"
stage_doc_file "$REPO" "g-docs/j1a.md"
echo "  staged: g-docs/j1a.md (DOC bucket only); no sentinels written"
run_precommit "$REPO"
check "j1a: exit non-zero, doc-only unstamped" "$([ "$LAST_CODE" -ne 0 ] && echo 1 || echo 0)" "exit=$LAST_CODE"
LC_ERR=$(printf '%s' "$LAST_ERR" | tr '[:upper:]' '[:lower:]')
check "j1a: reason names doc" "$(case "$LC_ERR" in *doc*) echo 1;; *) echo 0;; esac)" "stderr='$LAST_ERR'"

echo "  j1b: fresh repo, tier full, doc-only staged, STALE doc sentinel (stamp taken before content changed+restaged) -> deny"
REPO=$(new_repo "j1b-doc-stale-sentinel")
gate_tier "$REPO" full
initial_commit "$REPO"
stage_doc_file "$REPO" "g-docs/j1b.md"
TREE=$(git -C "$REPO" write-tree)
HEAD=$(git -C "$REPO" rev-parse --verify HEAD)
WT=$(git -C "$REPO" rev-parse --show-toplevel)
write_sentinel "$REPO/.claude/g-forge-docs-approved" "$TREE" "$HEAD" "$WT"
echo "  doc stamp taken: ts=$TREE head=$HEAD worktree=$WT"
printf '# doc changed\n' > "$REPO/g-docs/j1b.md"
git -C "$REPO" add g-docs/j1b.md
NEWTREE=$(git -C "$REPO" write-tree)
echo "  staged doc content changed post-stamp; new write-tree=$NEWTREE (differs from stamped ts=$TREE: $([ "$NEWTREE" != "$TREE" ] && echo yes || echo NO))"
run_precommit "$REPO"
check "j1b: exit non-zero on stale doc sentinel" "$([ "$LAST_CODE" -ne 0 ] && echo 1 || echo 0)" "exit=$LAST_CODE"
echo

# ============================================================================
echo "--- Scenario j2: DOC-only class, only a fully valid CODE sentinel present -> deny naming doc ---"
REPO=$(new_repo "j2-doc-only-code-sentinel")
gate_tier "$REPO" full
initial_commit "$REPO"
stage_doc_file "$REPO" "g-docs/j2.md"
TREE=$(git -C "$REPO" write-tree)
HEAD=$(git -C "$REPO" rev-parse --verify HEAD)
WT=$(git -C "$REPO" rev-parse --show-toplevel)
write_sentinel "$REPO/.claude/g-forge-approved" "$TREE" "$HEAD" "$WT"
echo "  staged: g-docs/j2.md (DOC bucket only); fully VALID code sentinel written (ts=$TREE head=$HEAD worktree=$WT); no doc sentinel"
run_precommit "$REPO"
check "j2: exit non-zero, valid code sentinel does not substitute for doc sign-off" "$([ "$LAST_CODE" -ne 0 ] && echo 1 || echo 0)" "exit=$LAST_CODE"
LC_ERR=$(printf '%s' "$LAST_ERR" | tr '[:upper:]' '[:lower:]')
check "j2: reason names doc" "$(case "$LC_ERR" in *doc*) echo 1;; *) echo 0;; esac)" "stderr='$LAST_ERR'"
echo

# ============================================================================
echo "--- Scenario j3: DOC-only class, valid doc sentinel -> pass + consume ---"
REPO=$(new_repo "j3-doc-valid")
gate_tier "$REPO" full
initial_commit "$REPO"
stage_doc_file "$REPO" "g-docs/j3.md"
TREE=$(git -C "$REPO" write-tree)
HEAD=$(git -C "$REPO" rev-parse --verify HEAD)
WT=$(git -C "$REPO" rev-parse --show-toplevel)
write_sentinel "$REPO/.claude/g-forge-docs-approved" "$TREE" "$HEAD" "$WT"
echo "  staged: g-docs/j3.md (DOC bucket only); valid doc sentinel: ts=$TREE head=$HEAD worktree=$WT"
run_precommit "$REPO"
check "j3: exit 0 on matching doc sentinel" "$([ "$LAST_CODE" -eq 0 ] && echo 1 || echo 0)" "exit=$LAST_CODE"
check "j3: doc sentinel consumed (file gone) immediately after" "$([ ! -f "$REPO/.claude/g-forge-docs-approved" ] && echo 1 || echo 0)" "file still present: $REPO/.claude/g-forge-docs-approved"
echo

# ============================================================================
echo "--- Scenario k: conflicted/unmerged index -> write-tree failure -> deny (with canary) ---"
REPO=$(new_repo "k-conflict")
gate_tier "$REPO" full
initial_commit "$REPO"
BASE_BRANCH=$(git -C "$REPO" branch --show-current)
printf 'line1\nline2\nline3\n' > "$REPO/conflict.txt"
git -C "$REPO" add conflict.txt
git -C "$REPO" commit -q -m "base conflict file"
echo "  base branch=$BASE_BRANCH; base commit for conflict.txt established"
git -C "$REPO" checkout -q -b branch-a
printf 'line1\nA-CHANGE\nline3\n' > "$REPO/conflict.txt"
git -C "$REPO" add conflict.txt
git -C "$REPO" commit -q -m "branch-a edits line2"
git -C "$REPO" checkout -q "$BASE_BRANCH"
git -C "$REPO" checkout -q -b branch-b
printf 'line1\nB-CHANGE\nline3\n' > "$REPO/conflict.txt"
git -C "$REPO" add conflict.txt
git -C "$REPO" commit -q -m "branch-b edits line2 (conflicting)"
echo "  merging branch-a into branch-b (expect conflict)..."
git -C "$REPO" merge branch-a >/dev/null 2>&1
UNMERGED=$(git -C "$REPO" ls-files -u)
echo "  canary: git ls-files -u output:"
echo "$UNMERGED"
check "k: canary - unmerged index present (git ls-files -u non-empty)" "$([ -n "$UNMERGED" ] && echo 1 || echo 0)" "ls-files -u produced no output"
WT_ERR=$(git -C "$REPO" write-tree 2>&1)
WT_RC=$?
echo "  canary: standalone 'git write-tree' exit=$WT_RC output='$WT_ERR' (expected non-zero)"
check "k: canary - standalone git write-tree fails on conflicted index" "$([ "$WT_RC" -ne 0 ] && echo 1 || echo 0)" "write-tree rc=$WT_RC output='$WT_ERR'"
run_precommit "$REPO"
check "k: exit non-zero, hook denies on write-tree failure" "$([ "$LAST_CODE" -ne 0 ] && echo 1 || echo 0)" "exit=$LAST_CODE"
LC_ERR=$(printf '%s' "$LAST_ERR" | tr '[:upper:]' '[:lower:]')
check "k: reason mentions write-tree/unmerged/conflict" "$(case "$LC_ERR" in *write-tree*|*unmerged*|*conflict*) echo 1;; *) echo 0;; esac)" "stderr='$LAST_ERR'"
echo

# ============================================================================
echo "--- Scenario l: ambiguous worktree resolution (separate-git-dir) -> deny (with canary) ---"
SEP_STORAGE="$BASE/l-separate-git-storage"
SEP_REPO="$BASE/l-separate-repo"
mkdir -p "$SEP_STORAGE"
mkdir -p "$SEP_REPO"
(
    cd "$SEP_REPO" || exit 99
    git init --separate-git-dir "$SEP_STORAGE" -q
    git config user.email "test@g-forge.local"
    git config user.name "g-forge-test"
    printf 'seed\n' > README.md
    git add README.md
    git commit -q -m "seed"
)
stage_code_file "$SEP_REPO" "hooks/l.sh"
echo "  repo: separate-git-dir construction (storage=$SEP_STORAGE, worktree=$SEP_REPO); no .claude/integration-tier anywhere"
CANARY_OUT=$(
    cd "$SEP_REPO" || exit 99
    . "$REPO_ROOT/hooks/lib/worktree-resolve.sh"
    gf_resolve_primary_claude_dir
)
CANARY_RC=$?
echo "  canary: gf_resolve_primary_claude_dir sourced+called directly with cwd=$SEP_REPO -> rc=$CANARY_RC stdout='$CANARY_OUT'"
check "l: canary - gf_resolve_primary_claude_dir rejects separate-git-dir (rc non-zero)" "$([ "$CANARY_RC" -ne 0 ] && echo 1 || echo 0)" "rc=$CANARY_RC stdout='$CANARY_OUT'"
check "l: canary - gf_resolve_primary_claude_dir stdout empty on reject" "$([ -z "$CANARY_OUT" ] && echo 1 || echo 0)" "stdout='$CANARY_OUT'"
run_precommit "$SEP_REPO"
check "l: exit non-zero, hook denies on ambiguous worktree resolution" "$([ "$LAST_CODE" -ne 0 ] && echo 1 || echo 0)" "exit=$LAST_CODE"
LC_ERR=$(printf '%s' "$LAST_ERR" | tr '[:upper:]' '[:lower:]')
HAS_RESOLVE=0
case "$LC_ERR" in *resolve*) HAS_RESOLVE=1 ;; esac
HAS_WORKTREE=0
case "$LC_ERR" in *worktree*) HAS_WORKTREE=1 ;; esac
check "l: reason contains 'resolve'" "$HAS_RESOLVE" "stderr='$LAST_ERR'"
check "l: reason contains 'worktree'" "$HAS_WORKTREE" "stderr='$LAST_ERR'"
echo

# ============================================================================
echo "=== SUMMARY ==="
echo "PASS: $TOTAL_PASS"
echo "FAIL: $TOTAL_FAIL"

rm -rf "$BASE"

if [ "$TOTAL_FAIL" -ne 0 ]; then
    exit 1
fi
exit 0
