#!/bin/bash
# build-index.sh — PostToolUse hook.
# Fires after every git commit. Regenerates .claude/skills/project-context/SKILL.md
# with a machine-derived project map so agents start warm instead of discovering
# structure via tool calls.

INPUT=$(cat)
CMD=$(echo "$INPUT" | python3 -c "
import json, sys
try:
    d = json.load(sys.stdin)
    cmd = d.get('tool_input', {}).get('command', '') or d.get('command', '')
    print(cmd)
except Exception:
    pass
" 2>/dev/null)

echo "$CMD" | grep -q "git commit" || exit 0

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || echo "unknown")

mkdir -p .claude/skills/project-context

# ── Active milestone ────────────────────────────────────────────────────────
MILESTONE=$(grep -m1 'Active context:' todo.md 2>/dev/null \
  | sed 's/.*Active context:[[:space:]]*//' \
  || grep -m1 'In progress' ROADMAP.md 2>/dev/null \
  | sed 's/^[[:space:]]*//' \
  || echo "none")

# ── Source tree ─────────────────────────────────────────────────────────────
# Directories 1-3 levels deep, noise filtered, with file counts
TREE=$(find . -mindepth 1 -maxdepth 3 -type d \
  | grep -vE '\.(git|next|venv|venv3|env|tox|mypy_cache|pytest_cache|ruff_cache)|node_modules|__pycache__|dist/|build/|\.cache|coverage|\.turbo' \
  | sort \
  | while read -r dir; do
      count=$(find "$dir" -maxdepth 1 -type f 2>/dev/null | wc -l | tr -d ' ')
      [ "$count" -gt 0 ] && printf "  %-40s (%s files)\n" "$dir" "$count"
    done \
  | head -35)

# ── Recent commits ──────────────────────────────────────────────────────────
COMMITS=$(git log --oneline -10 2>/dev/null || echo "no commits")

# ── Last commit changed files ───────────────────────────────────────────────
if git rev-parse HEAD~1 >/dev/null 2>&1; then
  CHANGED=$(git diff HEAD~1 --name-only 2>/dev/null | head -20 | sed 's/^/  /')
else
  CHANGED=$(git diff-tree --no-commit-id -r --name-only HEAD 2>/dev/null | head -20 | sed 's/^/  /')
fi

# ── Dependency summary ───────────────────────────────────────────────────────
DEPS=""

if [ -f package.json ]; then
  DEPS=$(python3 -c "
import json, sys
try:
    d = json.load(open('package.json'))
    deps = {**d.get('dependencies', {}), **d.get('devDependencies', {})}
    pairs = [f'{k} {v}' for k, v in list(deps.items())[:10]]
    print(' · '.join(pairs))
except Exception as e:
    print('(parse error)')
" 2>/dev/null)
fi

if [ -z "$DEPS" ] && [ -f requirements.txt ]; then
  DEPS=$(grep -v '^\s*#' requirements.txt 2>/dev/null \
    | grep -v '^\s*$' | head -10 | tr '\n' ' · ' | sed 's/ · $//')
fi

if [ -z "$DEPS" ] && [ -f pyproject.toml ]; then
  DEPS=$(grep -A20 '^\[project\]' pyproject.toml 2>/dev/null \
    | grep 'dependencies' | head -5)
fi

if [ -z "$DEPS" ] && [ -f Cargo.toml ]; then
  DEPS=$(grep -A30 '^\[dependencies\]' Cargo.toml 2>/dev/null \
    | grep -v '^\[' | grep '=' | head -10 | tr '\n' ' · ' | sed 's/ · $//')
fi

[ -z "$DEPS" ] && DEPS="(no manifest found)"

# ── Write skill file ─────────────────────────────────────────────────────────
cat > .claude/skills/project-context/SKILL.md << SKILLEOF
---
name: project-context
description: Current project structure map — source tree, recent commits, active milestone, and dependencies. Auto-updated on every git commit. Preloaded into code-lead, wave-planner, task-decomposer, and architect agents.
---

<!-- Auto-generated by G-Forge build-index.sh — do not edit manually. Updated: ${TIMESTAMP} -->

## Active milestone
${MILESTONE}

## Source tree
${TREE}

## Recent commits
${COMMITS}

## Files changed in last commit
${CHANGED}

## Key dependencies
${DEPS}
SKILLEOF

exit 0
